[service]
AppMode = debug
HttpPort = :3000

[mysql]
DB = mysql
DbHost = 127.0.0.1
DbPort = 3306
DbUser = root
DbPassword = 011214
DbName = mall_db_tmp

[redis]
RedisDb = redis
RedisAddr = 127.0.0.1:6379
RedisPw =
RedisDbName = 0

[os]
R2_AccessKey    = bf84da322292bf00893563058c6aa8ab
R2_SecretKey    = d7257bd31b7ffc41831f9dfdc84639f6151f21202ba74c9e2d710c9ca20a1803
;token_value = cfut_xEKiscobdkCYY9fcjt0jOhw9zTu4WqbobyDdkW1b991d5321
R2_Bucket       = gin-mall
R2_AccountId    = d7bccd59b8a1eeff441fd5af327a65be
R2_Domain       = https://pub-e093b133cbcb4ed6993d35eafa836eb3.r2.dev

[email]
ValidEmail = http://localhost:8080/#/vaild/email/
SmtpHost = smtp.qq.com
SmtpEmail = 3214244326@qq.com
SmtpPass = gkwxxtqcdihqdfja

[path]
Host = http://127.0.0.1
ProductPath = /static/imgs/product/
AvatarPath = /static/imgs/Avatar/